### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '*.mat'

### ISSUE THREAD

**Issue by pumpumpum1** [yijingru/Vertebra-Landmark-Detection#1]
Hello, tell me what should be contained in .mat files or show an example that was used in your code?

**Comment by yijingru** [comment]
Hi, the mat file contains the annotations of the landmarks. You can change the code to adapt it to your own data. Or you can download the dataset listed in https://aasce19.grand-challenge.org/Home/.

**Comment by pumpumpum1** [comment]
Oh, thank you. I try to can change the code to adapt to my data, but there was a problem with mat files. I have only the source images and their masks.

**Comment by pumpumpum1** [comment]
I can not download the dataset.
![image](https://user-images.githubusercontent.com/60422917/79088429-444ae680-7d4b-11ea-874f-8066b10bd576.png)

**Comment by yijingru** [comment]
I think you have to sign in first.  The mat file should provide the coordinates of the landmarks, as in dataset.py, 'pts' is loaded from the .mat file, 'pts' is a 2D array or matrix with the size of N x 2 (N=68).
    def load_gt_pts(self, annopath):
        pts = loadmat(annopath)['p2']   # num x 2 (x,y)
        pts = rearrange_pts(pts)
        return pts

**Comment by pumpumpum1** [comment]
Even after I went in, I did not have access to files.
It turns out that I have to create these mat files myself. I would like to clarify, do these files contain the coordinates of all the vertebrae?

**Comment by yijingru** [comment]
Yes, these mat files contain the coordinates of the corners of the vertebrae. You can adapt the code to your own annotations by replacing the load_gt_pts function in dataset.py

About the dataset, you can send your requirements here http://spineweb.digitalimaginggroup.ca/dataset.php.

**Comment by pumpumpum1** [comment]
Thanks a lot. I'll try!

**Comment by leilaShen** [comment]
Hi  since the data downloading link is not available for me, would  you upload the trained model file? Thanks a lot! @yijingru

**Comment by yijingru** [comment]
> Hi since the data downloading link is not available for me, would you upload the trained model file? Thanks a lot! @yijingru

The pretrained weights are shared now.

**Comment by chenyao96** [comment]
I am trying to change the code to my label:
def load_gt_pts(self, annopath):
      pts = loadmat(annopath)['p2'] # num x 2 (x,y)
      pts = rearrange_pts(pts)
      return pts
Hi, when returns pts, I want to confirm whether these pts are arranged in order.
such as this:
[[x1,y1],
 [x2,y2],
 ......
 [x67,y67]
]
Thank you for your reply

**Comment by UgurOzcanFited** [comment]
Hello, I am getting this error. Is there a problem on my .mat file? I downloaded the train and test images and labels. I am converting from .csv to .mat files. Succeed this. But I am not train the images and labels. Can you help me?

```javascript

Setting up data...
Starting training...
----------
Epoch: 1/50 
[[21.593  11.619   2.3353]]
[[38.967 11.978 34.892]]
[[35.528 29.172 15.598]]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    is_object.train_network(args)
  File "/home/ugur/Downloads/Fited-calismalar/Vertebra-Landmark-Detection-master/train.py", line 123, in train_network
    epoch_loss = self.run_epoch(phase='train',
  File "/home/ugur/Downloads/Fited-calismalar/Vertebra-Landmark-Detection-master/train.py", line 150, in run_epoch
    for data_dict in data_loader:
  File "/home/ugur/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/ugur/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/ugur/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/ugur/.local/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ugur/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ugur/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ugur/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ugur/Downloads/Fited-calismalar/Vertebra-Landmark-Detection-master/dataset.py", line 73, in __getitem__
    pts = self.load_annotation(index)   # num_obj x h x w
  File "/home/ugur/Downloads/Fited-calismalar/Vertebra-Landmark-Detection-master/dataset.py", line 60, in load_annotation
    pts = self.load_gt_pts(annoFolder)
  File "/home/ugur/Downloads/Fited-calismalar/Vertebra-Landmark-Detection-master/dataset.py", line 50, in load_gt_pts
    pts = rearrange_pts(pts)
  File "/home/ugur/Downloads/Fited-calismalar/Vertebra-Landmark-Detection-master/dataset.py", line 20, in rearrange_pts
    bl = pt_l[y_inds_l[1], :]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by Aboorvabs** [comment]
Please help me download the dataset
